# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: moveit_arm_controller
  joint_model_group_pose: Home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_back_hinge
    - drum_back_hinge
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - grabber_joint1
    - grabber_joint2
    - left_wheel_back_hinge
    - left_wheel_front_hinge
    - right_wheel_back_hinge
    - right_wheel_front_hinge
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: paver_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5

#moveit_arm_controller_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#    - joint1
#    - joint2
#    - joint3
#    - joint4
#    - joint5
#  gains:
#    joint1:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    joint2:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    joint3:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    joint4:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    joint5:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1