//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosMessages
{
    [Serializable]
    public class StdMessageMsg : Message
    {
        public const string k_RosMessageName = "RosMessages/StdMessage";
        public override string RosMessageName => k_RosMessageName;

        public float data;

        public StdMessageMsg()
        {
            this.data = 0.0f;
        }

        public StdMessageMsg(float data)
        {
            this.data = data;
        }

        public static StdMessageMsg Deserialize(MessageDeserializer deserializer) => new StdMessageMsg(deserializer);

        private StdMessageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "StdMessageMsg: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
