FROM mybase

RUN apt-get update && apt-get install -y \
    software-properties-common \
    python3 \
    python3-pip

RUN pip3 install scipy

RUN add-apt-repository -y ppa:ubuntugis/ppa

RUN apt-get update && apt-get install -y \ 
    gdal-bin \
    python-gdal \
    python3-gdal 

ADD queued_dems /tmp/queued_dems
ADD dem_results /tmp/dem_results
COPY testGdal.py /tmp/
COPY localMaxima.py /tmp/
COPY sample_all_dems.sh /tmp/

CMD ["sh", "./tmp/sample_all_dems.sh"]
