//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.EzrassorSwarmControl
{
    [Serializable]
    public class GetRoverStatusResponse : Message
    {
        public const string k_RosMessageName = "ezrassor_swarm_control/GetRoverStatus";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose;
        public sbyte battery;

        public GetRoverStatusResponse()
        {
            this.pose = new Geometry.PoseMsg();
            this.battery = 0;
        }

        public GetRoverStatusResponse(Geometry.PoseMsg pose, sbyte battery)
        {
            this.pose = pose;
            this.battery = battery;
        }

        public static GetRoverStatusResponse Deserialize(MessageDeserializer deserializer) => new GetRoverStatusResponse(deserializer);

        private GetRoverStatusResponse(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.battery);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.battery);
        }

        public override string ToString()
        {
            return "GetRoverStatusResponse: " +
            "\npose: " + pose.ToString() +
            "\nbattery: " + battery.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
