//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.EzrassorSwarmControl
{
    [Serializable]
    public class PreemptPathRequest : Message
    {
        public const string k_RosMessageName = "ezrassor_swarm_control/PreemptPath";
        public override string RosMessageName => k_RosMessageName;


        public PreemptPathRequest()
        {
        }
        public static PreemptPathRequest Deserialize(MessageDeserializer deserializer) => new PreemptPathRequest(deserializer);

        private PreemptPathRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "PreemptPathRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
