FROM mybase

RUN apt-get update && apt-get install -y \
    software-properties-common \
    python3

RUN add-apt-repository -y ppa:ubuntugis/ppa

RUN apt-get update && apt-get install -y \
    gdal-bin \
    python-gdal \
    python3-gdal

ADD /convert2tif/queued_dems /tmp/queued_dems
ADD /convert2tif/results /tmp/results
COPY /convert2tif/script_convert.sh /tmp/

CMD ["sh", "./tmp/script_convert.sh"]
