set(_CATKIN_CURRENT_PACKAGE "ez_gui")
set(ez_gui_VERSION "0.0.0")
set(ez_gui_MAINTAINER "Christopher Taliafero <taliaferrodev@gmail.com>")
set(ez_gui_PACKAGE_FORMAT "2")
set(ez_gui_BUILD_DEPENDS "roscpp" "rospy" "rviz")
set(ez_gui_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "rviz")
set(ez_gui_BUILDTOOL_DEPENDS "catkin")
set(ez_gui_BUILDTOOL_EXPORT_DEPENDS )
set(ez_gui_EXEC_DEPENDS "roscpp" "rospy" "rviz")
set(ez_gui_RUN_DEPENDS "roscpp" "rospy" "rviz")
set(ez_gui_TEST_DEPENDS )
set(ez_gui_DOC_DEPENDS )
set(ez_gui_URL_WEBSITE "")
set(ez_gui_URL_BUGTRACKER "")
set(ez_gui_URL_REPOSITORY "")
set(ez_gui_DEPRECATED "")