set(_CATKIN_CURRENT_PACKAGE "ez_gui")
set(ez_gui_VERSION "0.1.0")
set(ez_gui_MAINTAINER "Hansuto <taliaferrodev@gmail.com>")
set(ez_gui_PACKAGE_FORMAT "1")
set(ez_gui_BUILD_DEPENDS "qt_build" "roscpp" "libqt4-dev" "cv_bridge" "image_transport" "std_msgs" "sensor_msgs")
set(ez_gui_BUILD_EXPORT_DEPENDS "qt_build" "roscpp" "libqt4-dev" "cv_bridge" "image_transport" "std_msgs" "sensor_msgs")
set(ez_gui_BUILDTOOL_DEPENDS "catkin")
set(ez_gui_BUILDTOOL_EXPORT_DEPENDS )
set(ez_gui_EXEC_DEPENDS "qt_build" "roscpp" "libqt4-dev" "cv_bridge" "image_transport" "std_msgs" "sensor_msgs")
set(ez_gui_RUN_DEPENDS "qt_build" "roscpp" "libqt4-dev" "cv_bridge" "image_transport" "std_msgs" "sensor_msgs")
set(ez_gui_TEST_DEPENDS )
set(ez_gui_DOC_DEPENDS )
set(ez_gui_URL_WEBSITE "")
set(ez_gui_URL_BUGTRACKER "")
set(ez_gui_URL_REPOSITORY "")
set(ez_gui_DEPRECATED "")