//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.EzrassorSwarmControl
{
    [Serializable]
    public class PathMsg : Message
    {
        public const string k_RosMessageName = "ezrassor_swarm_control/Path";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg[] path;

        public PathMsg()
        {
            this.path = new Geometry.PointMsg[0];
        }

        public PathMsg(Geometry.PointMsg[] path)
        {
            this.path = path;
        }

        public static PathMsg Deserialize(MessageDeserializer deserializer) => new PathMsg(deserializer);

        private PathMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.path, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.path);
            serializer.Write(this.path);
        }

        public override string ToString()
        {
            return "PathMsg: " +
            "\npath: " + System.String.Join(", ", path.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
