name: dev

on:
  push: 
    branches:
      - github-actions

jobs:

  rostest:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Run rostest on repository
        run: |
          docker build -t ez-rassor_rostest -f .github/build/Dockerfile .
          docker run ez-rassor_rostest